name: Rebuild GitHub Pages

on:
  schedule:
    - cron: '0 4 * * 0' # every Sunday at 4 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git commit --allow-empty -m "Trigger Pages rebuild [skip ci]"
          git push
